#!/bin/sh
# .___________. __    __   _______
# |           ||  |  |  | |   ____|
# `---|  |----`|  |__|  | |  |__
#     |  |     |   __   | |   __|
#     |  |     |  |  |  | |  |____
#     |__|     |__|  |__| |_______|
#
# .___________. _______ .______      .___  ___.
# |           ||   ____||   _  \     |   \/   |
# `---|  |----`|  |__   |  |_)  |    |  \  /  |
#     |  |     |   __|  |      /     |  |\/|  |
#     |  |     |  |____ |  |\  \----.|  |  |  |
#     |__|     |_______|| _| `._____||__|  |__|
#
# Copyright (C) 2019-2021 naheel-azawy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# THETERM is used to automatically open terminal emulators in tmux
# sessions and connect to deattached sessions. It also tries to start
# in the directory of the current X window.
# Depends on: tmux, xprop, xdotool

# Name of this script
BINAME=$(basename "$0")

# Full path to this script
BINPATH=$(realpath "$0")

# Get last PID before any mess happen
# example:
# fish(13890)---bash(23328)---lf(6422)-+-lf(6428)-+-{lf}(6432)
#                                 ^    |          |-{lf}(6433)
#                                 |    |          |    ...
#                                 |    |-sh(6431)
#                 "Get this" --- /     |-{lf}(6423)
#                                      |   ...
getgoodpid_from_tree() {
    PID="$1"
    [ "$TREE_DIF" = '' ] && TREE_DIF=0
    pstree -lpAT "$PID" |
        # Ignore subprocesses of this script
        awk -F"---$BINAME" '{print $1}' |
        # First line
        head -n1 |
        # Left side in the left tree
        awk -F'---' '{print $NF}' |
        # Get rid of garbage on the right
        awk -F')' '{print $1}' |
        # The command and PID, to be evaled
        sed -En 's/(.+)\(([0-9]+).*/CMD="\1";PID=\2/p'
}

# Get the PID of the last process controlling stdout.
# However this is too expensive. Maybe try `fuser -vm`.
# But that lists all processes controlling /dev/pts.
# For now we'll stick to lsof for convenience. Might
# change this in the near future if turners out to be
# too too slow.
getgoodpid_from_of() {
    lsof "/proc/$PID/fd/1" | tail -n 1 |
        awk '{print "CMD="$1"; PID="$2}'
}

# Get the current working directory based on the focused X window
xpwd() {

    CWD=''

    # Get window ID
    ID=$(xdotool getactivewindow)

    # Window details
    DET=$(xprop -id "$ID")

    # Get PID of process whose window this is
    PID=$(echo "$DET" | grep -m 1 PID | cut -d " " -f 3)

    # Window class name
    CLASS=$(echo "$DET" | grep -m 1 WM_CLASS | sed -En 's/.+"(.+)".*/\1/p')

    # Class specific special cases
    case "$CLASS" in
        Evince)
            # The PDF file must be under on the the process's file descriptors
            FDS="/proc/$PID/fd"
            for f in $FDS/*; do
                l="$(readlink "$f")"
                if echo "$l" | grep -q '\.pdf$'; then
                    CWD=$(dirname "$l")
                    PID=''
                    break
                fi
            done
            ;;

        jetbrains-studio)
            P=$(echo "$DET" |
                    sed -En 's@_NET_WM_NAME.+\".*\[(.+)\].*\[.*\"@\1@p' |
                    sed "s@~@$HOME@")
            if ! [ -d "$P" ]; then
                P=$(echo "$DET" |
                        sed -En 's@_NET_WM_NAME.+\".*\[(.+)\].*\"@\1@p' |
                        sed "s@~@$HOME@")
            fi
            if [ -d "$P" ]; then
                CWD="$P"
                PID=''
            fi
            ;;
    esac

    if [ -n "$PID" ]; then

        # is an emacs instance
        if ps -p "$PID" -o command | grep emacs -q; then

            CWD=$(emacsclient --no-wait --eval '(buffer-file-name (switch-to-buffer (other-buffer (current-buffer) 1))))' |
                      cut -d '"' -f2)
            CWD=$(dirname "$CWD")

        else

            eval "$(getgoodpid_from_tree "$PID")"
            # Get tmux PID if any
            # Get the tmux client connected session PID
            TMUXC=$(tmux list-clients -F '#{client_pid} #{session_name}' | grep "$PID")
            [ "$TMUXC" != '' ] && {
                # Get tmux session
                TMUXS=$(echo "$TMUXC" | awk '{print $2}')
                # if only tmux session needed
                [ "$1" = '--tmux-session' ] && echo "$TMUXS" && return
                # PID running on the tmux session
                PID=$(tmux list-sessions -F "#{?#{==:#{session_name},$TMUXS},aaa,nnn} #{pane_pid}" | grep aaa | awk '{print $2}')
            }
            eval "$(getgoodpid_from_of "$PID")"
            # If we find the working directory, run the command in that directory
            if [ -e "/proc/$PID/cwd" ]; then
                CWD=$(readlink "/proc/$PID/cwd")
            fi
        fi

    fi

    case "$1" in
        --good-pid)
            echo "$PID" ;;
        --info)
            [ "$CMD" ] || CMD=$(ps -p "$PID" -o command -h)
            echo "PID=$PID"
            echo "CMD='$CMD'"
            echo "CWD='$CWD'"
            echo "TMUX_SESSION='$TMUXS'" ;;
        *)
            echo "$CWD" ;;
    esac
}

# Get the current tmux session based on the focused X window
tmuxsession() {
    xpwd --tmux-session
}

# Output a good PID the represents whats actually focused on the screen
good_pid() {
    xpwd --good-pid
}

# Outputs general info about the current terminal window. To be `eval`ed
info() {
    xpwd --info
}

# Start a tmux session or attach to deattached session if any
tmuxquick() {
    if [ "$TS" ]; then
        LS=$(tmux ls -F '#{session_name}' | grep "$TS")
        if [ "$LS" ]; then
            exec tmux a -t "$TS"
        else
            exec tmux new-session -s "$TS" "$@"
        fi
    else
        S=$(tmux ls -F '#{session_name} #{?session_attached,aaa,nnn}' 2>/dev/null \
                | grep nnn | grep -v ignored | tail -n 1 | awk '{print $1}')
        # If no unattached sessions or args available, create new one
        [ ! "$S" ] || [ $# != 0 ] && exec tmux new-session "$@"
        # If any tmux session is not attached, attach to it
        exec tmux a -t "$S"
    fi
}

# Start THE terminal
starterm() {
    if [ "$1" = '--nocd' ]; then
        shift
    else
        cd "$(xpwd)" ||:
    fi
    if [ ! "$THETERM_TERM" ]; then
        if   command -v st    >/dev/null; then THETERM_TERM=st
        elif command -v urxvt >/dev/null; then THETERM_TERM=urxvt
        elif command -v xterm >/dev/null; then THETERM_TERM=xterm
        else echo 'No supported terminal found' && return 1
        fi
    fi
    if [ "$TS" ]; then
        exec "$THETERM_TERM" $TARGS -e "$BINPATH" --tmuxs "$TS" "$@"
    else
        exec "$THETERM_TERM" $TARGS -e "$BINPATH" --tmux "$@"
    fi
}

# Ignore the current tmux session in the x window
tmuxignore() {
    S="$1"
    [ "$S" = '' ] && S=$(tmuxsession)
    [ "$S" = '' ] && return
    echo "$S" | grep -q 'ignored' && return # only if not already ignored
    tmux rename-session -t "$S" "ignored-$S"
    echo "ignored-$S"
}

# Unignore the current tmux session in the x window
tmuxunignore() {
    S="$1"
    [ "$S" = '' ] && S=$(tmuxsession)
    [ "$S" = '' ] && return
    N=$(echo "$S" | sed -En 's/ignored-(.+)/\1/p')
    echo "$S" | grep -q 'ignored' && \
        tmux rename-session -t "$S" "$N" && \
        echo "$N"
}

# Unignore all tmux sessions
tmuxunignoreall() {
    tmux ls -F '#{session_name}' | grep 'ignored-' | \
        while read -r line; do
            tmuxunignore "$line" >/dev/null
        done
}

# Kill a terminal X window
# exit codes:
#  1: not a tmux session window
#  2: is tmux session but don't know how to exit
windowkill() {
    # Send keys base on the currnet command.

    TITLE=$(xdotool getactivewindow getwindowname)
    INFO=$(echo "$TITLE" |
               sed -En 's/.+ - tmux ([0-9]+):([0-9]+)/SESSION=\1;PID=\2/p')
    [ "$INFO" ] || return 1
    eval "$INFO"
    eval "$(getgoodpid_from_of "$PID")"

    # echo "$CMD $SESSION $PID"

    case "$CMD" in
        fish|zsh|xonsh|bash|dash|sh)
            tmux send-keys -t "$SESSION" C-c
            sleep .1
            tmux send-keys -t "$SESSION" 'exit 0' ENTER 2>/dev/null ||: ;;
        less|lf|ncmpcpp|mpd-notificatio|vis|gotop)
            tmux send-keys -t "$SESSION" 'q' ;;
        nano)
            tmux send-keys -t "$SESSION" C-x ;;
        emacs*)
            tmux send-keys -t "$SESSION" C-x C-c ;;
        alsamixer)
            tmux send-keys -t "$SESSION" ESCAPE ;;
        watch|python)
            tmux send-keys -t "$SESSION" C-c ;;
        *)
            notify-send "Couldn't kill '$CMD'"
            return 2 ;;
    esac
}

help() {
    echo "usage: $BINAME [OPTION]... [COMMANDS]
  -e, --command=COMMANDS        Execute the given COMMANDS in arguments
  --nocd                        Run without changing directory
  --tmux=COMMANDS               Starts a tmux session running the COMMANDS
  --tmux-ignore=TMUXSESSION     Ignore the TMUXSESSION
  --tmux-unignore=TMUXSESSION   Unignore the TMUXSESSION
  --tmux-unignore-all           Unignore all tmux sessions
  --info                        Print general info about the X window
  --xpwd                        Print working directory based on the X window
  --tmux-session                Print tmux session based on the X window
  --kill-window                 Attempt to kill a terminal X window
  -h, --help                    Show this help"
    exit 1
}

main() {
    [ "$1" = '-s' ] && TS="$2"    && shift 2
    [ "$1" = '-a' ] && TARGS="$2" && shift 2
    case "$1" in
        --info)                         info                ;;
        --xpwd)                         xpwd                ;;
        --tmux-session)                 tmuxsession         ;;
        --good-pid)                     good_pid            ;;
        --tmux)              shift   && tmuxquick       "$@";;
        --tmuxs)  TS="$2" && shift 2 && tmuxquick       "$@";;
        --tmux-ignore)       shift   && tmuxignore      "$@";;
        --tmux-unignore)     shift   && tmuxunignore    "$@";;
        --tmux-unignore-all)            tmuxunignoreall     ;;
        --kill-window)                  windowkill          ;;
        --command|-e)        shift   && starterm        "$@";;
        --nocd)              shift   && starterm --nocd "$@";;
        --help|-h)                      help                ;;
        *)                              starterm        "$@";;
    esac
}

main "$@"
